// *************************************************************
// project:  graphql-aspnet
// --
// repo: https://github.com/graphql-aspnet
// docs: https://graphql-aspnet.github.io
// --
// License:  MIT
// *************************************************************

namespace GraphQL.AspNet.Tests.Mocks
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json;
    using GraphQL.AspNet.Execution;
    using GraphQL.AspNet.Execution.Contexts;
    using GraphQL.AspNet.Execution.Variables;
    using GraphQL.AspNet.Interfaces.Execution;
    using GraphQL.AspNet.Interfaces.Logging;
    using GraphQL.AspNet.Interfaces.Schema;
    using GraphQL.AspNet.Interfaces.Security;
    using GraphQL.AspNet.Interfaces.Subscriptions;
    using GraphQL.AspNet.Schemas.Generation.TypeTemplates;
    using GraphQL.AspNet.Schemas.Structural;
    using NSubstitute;

    /// <summary>
    /// A test builder to create a subscription query context that can be
    /// passed to an execution pipeline.
    /// </summary>
    public class SubscriptionContextBuilder
    {
        private readonly IUserSecurityContext _seceurityContext;
        private readonly IQueryExecutionRequest _mockRequest;

        private readonly List<KeyValuePair<ItemPath, object>> _sourceData;

        private IServiceProvider _serviceProvider;
        private IQueryExecutionMetrics _metrics;
        private IGraphEventLogger _eventLogger;
        private ISubscriptionClientProxy _client;

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionContextBuilder" /> class.
        /// </summary>
        /// <param name="client">The client.</param>
        /// <param name="serviceProvider">The service provider.</param>
        /// <param name="securityContext">The security context.</param>
        public SubscriptionContextBuilder(
            ISubscriptionClientProxy client,
            IServiceProvider serviceProvider,
            IUserSecurityContext securityContext)
        {
            _client = client;
            _serviceProvider = serviceProvider;
            _seceurityContext = securityContext;
            _mockRequest = Substitute.For<IQueryExecutionRequest>();
            _mockRequest.OperationName.Returns(string.Empty);

            _sourceData = new List<KeyValuePair<ItemPath, object>>();

            _mockRequest.ToDataPackage().Returns((x) =>
                new AspNet.GraphQueryData()
                {
                    Query = _mockRequest.QueryText,
                    Variables = new InputVariableCollection(_mockRequest.VariableData),
                    OperationName = _mockRequest.OperationName,
                });
        }

        /// <summary>
        /// Adds a set of variables to use in the request.
        /// </summary>
        /// <param name="jsonDocument">The json document containing the variable data.</param>
        /// <returns>SubscriptionContextBuilder.</returns>
        public SubscriptionContextBuilder AddVariableData(string jsonDocument)
        {
            var variableData = JsonSerializer.Deserialize<InputVariableCollection>(jsonDocument);
            _mockRequest.VariableData.Returns(variableData);
            return this;
        }

        /// <summary>
        /// Adds the name of the operation to be executed to this instance.
        /// </summary>
        /// <param name="operationName">Name of the operation.</param>
        /// <returns>SubscriptionContextBuilder.</returns>
        public SubscriptionContextBuilder AddOperationName(string operationName)
        {
            _mockRequest.OperationName.Returns(operationName);
            return this;
        }

        /// <summary>
        /// Adds the metrics package to the query context that is being generated by this builder.
        /// </summary>
        /// <param name="metricsPackage">The metrics package.</param>
        /// <returns>SubscriptionContextBuilder.</returns>
        public SubscriptionContextBuilder AddMetrics(IQueryExecutionMetrics metricsPackage)
        {
            _metrics = metricsPackage;
            return this;
        }

        /// <summary>
        /// Adds the speficied query text as the query to execute.
        /// </summary>
        /// <param name="queryText">The query text.</param>
        /// <returns>SubscriptionContextBuilder.</returns>
        public SubscriptionContextBuilder AddQueryText(string queryText)
        {
            _mockRequest.QueryText.Returns(queryText);
            return this;
        }

        /// <summary>
        /// Adds the given logger instance to the contexts that this builder creates.
        /// </summary>
        /// <param name="eventLogger">The event logger.</param>
        /// <returns>SubscriptionContextBuilder.</returns>
        public SubscriptionContextBuilder AddLogger(IGraphEventLogger eventLogger)
        {
            _eventLogger = eventLogger;
            return this;
        }

        /// <summary>
        /// Adds a new default value that will be included in the built context.
        /// </summary>
        /// <param name="path">The field path representing the action to accept the parameter.</param>
        /// <param name="sourceData">The source data.</param>
        /// <returns>SubscriptionContextBuilder.</returns>
        public SubscriptionContextBuilder AddDefaultValue(ItemPath path, object sourceData)
        {
            _sourceData.Add(new KeyValuePair<ItemPath, object>(path, sourceData));
            return this;
        }

        /// <summary>
        /// Creates this query context instance that can be executed against the test server.
        /// </summary>
        /// <param name="subscriptionId">The subscription identifier to assign to the created sub.</param>
        /// <returns>GraphQueryContext.</returns>
        public virtual SubcriptionQueryExecutionContext Build(string subscriptionId = null)
        {
            subscriptionId = subscriptionId ?? Guid.NewGuid().ToString();
            var metaData = new MetaDataCollection();

            // unchangable items about the request
            var request = Substitute.For<IQueryExecutionRequest>();

            // updateable items about the request
            var context = new SubcriptionQueryExecutionContext(
                this.QueryRequest,
                _client,
                _serviceProvider,
                new QuerySession(),
                _seceurityContext,
                subscriptionId,
                metrics: _metrics,
                logger: _eventLogger);

            foreach (var kvp in _sourceData)
            {
                var mockField = Substitute.For<IGraphField>();
                mockField.FieldSource.Returns(GraphFieldSource.Action);
                mockField.ItemPath.Returns(kvp.Key);
                context.DefaultFieldSources.AddSource(mockField, kvp.Value);
            }

            return context;
        }

        /// <summary>
        /// Gets the mocked request as its currently defined by this builder.
        /// </summary>
        /// <value>The operation request.</value>
        public IQueryExecutionRequest QueryRequest => _mockRequest;
    }
}